### ISSUE TITLE
Potential issue in error handling

### ISSUE THREAD

**Issue by kstaken** [terascope/terafoundation#18]
reference to cluster looks problematic.

```
"name":"receiver","hostname":"vm1.tera3","pid":12,"level":50,"msg":"Worker crashed","time":"2015-08-18T20:59:22.665Z","v":0}
{"name":"receiver","hostname":"vm1.tera3","pid":12,"level":50,"msg":"cluster is not defined","time":"2015-08-18T20:59:22.672Z","v":0}
{"name":"receiver","hostname":"vm1.tera3","pid":13,"level":50,"msg":"cluster is not defined","time":"2015-08-18T20:59:22.666Z","v":0}
{"name":"receiver","hostname":"vm1.tera3","pid":12,"level":50,"msg":"ReferenceError: cluster is not defined\n    at process.shutdown (/app/source/lib/worker.js:19:33)\n    at process.emit (events.js:104:17)\n    at Signal.wrap.onsignal (node.js:655:46)","time":"2015-08-18T20:59:22.674Z","v":0}
{"name":"receiver","hostname":"vm1.tera3","pid":13,"level":50,"msg":"ReferenceError: cluster is not defined\n    at process.shutdown (/app/source/lib/worker.js:19:33)\n    at process.emit (events.js:104:17)\n    at Signal.wrap.onsignal (node.js:655:46)","time":"2015-08-18T20:59:22.692Z","v":0}
{"name":"receiver","hostname":"vm1.tera3","pid":1,"level":50,"msg":"Error Error: Redis connection to redis:6379 failed - connect ECONNREFUSED","time":"2015-08-18T20:59:22.994Z","v":0}
{"name":"receiver","hostname":"vm1.tera3","pid":12,"level":50,"msg":"Error Error: Redis connection to redis:6379 failed - connect ECONNREFUSED","time":"2015-08
```

**Comment by kstaken** [comment]
Haven't seen this again. Will reopen if needed.
