### ISSUE TITLE
Error when no config provided

### ISSUE THREAD

**Issue by kstaken** [terascope/terafoundation#44]
I forgot the -c and received this error.

```
$ node service.js ../config/import.yaml
Could not find a usable config.js at the path: /Users/kstaken/projects/tera1/import/config.yaml
/Users/kstaken/projects/opensource/terafoundation/node_modules/convict/lib/convict.js:235
  Object.keys(from).forEach(function(k) {
         ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at overlay (/Users/kstaken/projects/opensource/terafoundation/node_modules/convict/lib/convict.js:235:10)
    at Object.rv.load (/Users/kstaken/projects/opensource/terafoundation/node_modules/convict/lib/convict.js:376:7)
    at validateConfig (/Users/kstaken/projects/opensource/terafoundation/index.js:34:16)
    at module.exports (/Users/kstaken/projects/opensource/terafoundation/index.js:24:21)
    at Object.<anonymous> (/Users/kstaken/projects/tera1/import/service.js:4:43)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by kstaken** [comment]
I think this was an old version of terafoundation. closing.
