### ISSUE TITLE
node-webhdfs dependency issues

### ISSUE THREAD

**Issue by kstaken** [terascope/terafoundation#76]
The node-webhdfs dependency is locked to version 0.1.0

Also I noticed that the change that was committed still uses namenode_host and namenode_list. I thought it was decided that ONLY namenode_host was required. 

namenode_host: "namenode1"
namenode_host: ["namenode1"]
namenode_host: ["namenode1", "namenode2"]

Is there some reason it can't simply work like that?

**Comment by kstaken** [comment]
Maybe I jumped the gun on looking at this. The configuration is clearly inconsistent.

```
        namenode_host: {
            doc: 'a single host, or multiple hosts listed in an array',
            default: [],
            format: function(val) {
                if (typeof val === 'string') {
                    return;
                }
                if (Array.isArray(val)) {
                    if (val.length < 2) {
                        throw new Error("namenode_list must have at least two namenodes listed in the array")
                    }
                    return;
                }
                throw new Error('namenode_list configuration must be set to an array for high availability or a string')
            }
        },
```

And you get an error when starting teraslice.

```
/Users/kstaken/projects/opensource/terafoundation/lib/validate_configs.js:36
        throw new Error('Error validating configuration, error: ' + err.stack)
        ^

Error: Error validating configuration, error: SyntaxError: Unexpected token c
    at Object.parse (native)
    at coerce (/Users/kstaken/projects/opensource/terafoundation/node_modules/convict/lib/convict.js:300:29)
    at /Users/kstaken/projects/opensource/terafoundation/node_modules/convict/lib/convict.js:252:15
    at Array.forEach (native)
    at overlay (/Users/kstaken/projects/opensource/terafoundation/node_modules/convict/lib/convict.js:249:21)
    at Object.rv.load (/Users/kstaken/projects/opensource/terafoundation/node_modules/convict/lib/convict.js:454:7)
```
